# Generated by Django 3.1.4 on 2020-12-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_canchamodel_tipocanchamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('clienteId', models.AutoField(db_column='cli_id', primary_key=True, serialize=False, unique=True)),
                ('clienteNombre', models.CharField(db_column='cli_nombre', max_length=45)),
                ('clienteDni', models.CharField(db_column='cli_dni', max_length=8)),
                ('createAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_cliente',
            },
        ),
        migrations.CreateModel(
            name='TipoClienteModel',
            fields=[
                ('tipoClientId', models.AutoField(db_column='tcli_id', primary_key=True, serialize=False, unique=True)),
                ('tipoClienteDescuento', models.IntegerField(db_column='tcli_descuento')),
                ('tipoClienteNombre', models.CharField(db_column='tcli_nombre', max_length=45)),
                ('createAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_tipocliente',
            },
        ),
        migrations.CreateModel(
            name='RegistroModel',
            fields=[
                ('registroId', models.AutoField(db_column='reg_id', primary_key=True, serialize=False, unique=True)),
                ('registroPrecFinal', models.DecimalField(db_column='reg_prec_final', decimal_places=2, max_digits=5)),
                ('registroFechIni', models.DateTimeField(db_column='reg_fechin')),
                ('registroFechFin', models.DateTimeField(db_column='reg_fechfin')),
                ('createAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('estado', models.BooleanField(default=True)),
                ('canchaId', models.ForeignKey(db_column='can_id', on_delete=django.db.models.deletion.PROTECT, related_name='registrosCancha', to='administracion.canchamodel')),
                ('clienteId', models.ForeignKey(db_column='cli_id', on_delete=django.db.models.deletion.PROTECT, related_name='registrosCliente', to='administracion.clientemodel')),
            ],
            options={
                'db_table': 't_registro',
            },
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='tipoClienteId',
            field=models.ForeignKey(db_column='tcli_id', on_delete=django.db.models.deletion.PROTECT, related_name='clientesTipo', to='administracion.tipoclientemodel'),
        ),
    ]
