USE PLAYA_AQP;
USE PLAYA;

SELECT * FROM t_vehiculo;

#ORDER BY SIEMPRE VA AL FINAL DESPUES DE HABER DECLARADO LA O LAS TABLAS 
#ADMITE DOS VALORES ASC (ASCENDENTE) O DESC (DESCENDENTE) SI NO LE PONEMOS NADA TOMARA POR DEFECTO ASC

SELECT * FROM t_vehiculo ORDER BY veh_marca, veh_anio DESC;

#GROUP BY SE USAR PARA AGRUPAR LOS RESULTADOS DE UNA FUNCIÓN Y QUE RESPETE SUS PARAMETROS
#https://dev.mysql.com/doc/refman/8.0/en/sql-function-reference.html
SELECT veh_marca AS MARCA, COUNT(VEH_MARCA) AS TOTAL FROM t_vehiculo GROUP BY VEH_MARCA;